spring.application.name=Solid
spring.datasource.url=jdbc:mysql://localhost:3306/SOLIDDESIGN?createDatabaseIfNotExist=true
spring.datasource.username=root
# REPLACE THIS WITH YOUR REAL PASSWORD ONLY ON YOUR LOCAL MACHINE
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=9090
# REPLACE THIS WITH ENV VARIABLE IN PRODUCTION
jwt.secret-key=${JWT_SECRET}
management.endpoints.web.exposure.include=mappings

# Brevo SMTP
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9a0db5001@smtp-brevo.com
# --- THIS WAS THE PROBLEM ---
spring.mail.password=${MAIL_PASSWORD}
# ----------------------------
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Envelope MAIL FROM for DMARC alignment
spring.mail.properties.mail.smtp.from=mail@soliddesign.fit
# Header From used by our EmailService
spring.mail.from=mail@soliddesign.fit
# Enable SMTP debug logs in dev; disable in prod
spring.mail.properties.mail.debug=true